/** Sesiones de meditación guiada — Calma (con base neurocientífica) */
export const MEDITATIONS = [
  { id: 'breathing', name: 'Respiración consciente', icon: '🌬️', desc: 'Ancla tu mente en el ritmo del aire.', type: 'breathing', neuro: 'Exhalar largo activa nervio vago y parasimpático — baja cortisol en segundos.' },
  { id: 'body-scan', name: 'Escaneo corporal', icon: '🫁', desc: 'Recorre el cuerpo con atención amable.', type: 'steps', stepsKey: 'bodyScan', neuro: 'Entrena interocepción en ínsula — detectar señales corporales antes de que escalen.' },
  { id: 'gratitude', name: 'Gratitud', icon: '🙏', desc: 'Tres cosas concretas que hoy merecen tu gracias.', type: 'steps', stepsKey: 'gratitude', neuro: 'Activa corteza prefrontal medial y reduce actividad amigdalina en estudios de fMRI.' },
  { id: 'release', name: 'Soltar tensión', icon: '🫧', desc: 'Suelta hombros, mandíbula y lo que no necesitas cargar.', type: 'steps', stepsKey: 'release', neuro: 'Relajar músculo esquelético envía señal de seguridad al tronco encefálico — regula eje HPA.' },
  { id: 'presleep', name: 'Pre-sueño', icon: '🌙', desc: 'Baja el ritmo antes de dormir.', type: 'steps', stepsKey: 'presleep', neuro: 'Prepara ondas lentas (N3) y sistema glinfático — consolidación y limpieza nocturna.' },
  { id: 'prefocus', name: 'Pre-enfoque', icon: '🎯', desc: 'Claridad en 5 minutos antes de trabajar.', type: 'steps', stepsKey: 'prefocus', neuro: 'Activa red atencional dorsal (top-down) y desactiva red por defecto (rumiación).' },
  { id: 'walk', name: 'Caminata consciente', icon: '🚶', desc: 'Caminar lento, sintiendo cada paso.', type: 'steps', stepsKey: 'walk', neuro: 'Corteza motora + ínsula en sincronía — movimiento bilateral regula sistema nervioso autónomo.' },
  { id: 'loving', name: 'Bondad amorosa', icon: '💚', desc: 'Buenos deseos para ti y para alguien más.', type: 'steps', stepsKey: 'loving', neuro: 'Activa ínsula anterior y cíngulo — circuitos de empatía y regulación emocional.' },
]

export const MEDITATION_STEPS = {
  bodyScan: [
    { text: 'Cierra los ojos. Tres respiraciones profundas por la nariz.', duration: 35 },
    { text: 'Lleva la atención a los dedos de los pies. Nota temperatura y contacto.', duration: 40 },
    { text: 'Sube por tobillos, pantorrillas y rodillas. Sin juzgar, solo observa.', duration: 45 },
    { text: 'Muslos, cadera y zona baja del abdomen.', duration: 40 },
    { text: 'Siente el abdomen subir y bajar con cada respiración.', duration: 45 },
    { text: 'Pecho, espalda y hombros. Deja caer la tensión.', duration: 45 },
    { text: 'Brazos, manos y dedos. Relaja la mandíbula y la lengua.', duration: 40 },
    { text: 'Cuello, mandíbula, mejillas y frente.', duration: 40 },
    { text: 'Ojos, sienes y coronilla. Todo el cuerpo respira junto.', duration: 40 },
    { text: 'Toma un momento para sentir el cuerpo entero, en calma.', duration: 35 },
    { text: 'Mueve suavemente dedos y tobillos. Cuando estés listo, abre los ojos.', duration: 30 },
  ],
  gratitude: [
    { text: 'Siéntate cómodo. Respira lento tres veces.', duration: 30 },
    { text: 'Piensa en algo pequeño de hoy que te haya ayudado. Solo nómbralo mentalmente.', duration: 50 },
    { text: 'Recuerda a alguien que te haya acompañado, aunque sea con un mensaje.', duration: 50 },
    { text: 'Algo de tu cuerpo o tu salud que a menudo das por sentado.', duration: 50 },
    { text: 'Un lugar, un sonido o un momento que te dio paz hoy.', duration: 45 },
    { text: 'Lleva una mano al pecho. Siente gratitud sin forzar la emoción.', duration: 40 },
    { text: 'Abre los ojos. Si quieres, anótalo en tu diario después.', duration: 25 },
  ],
  release: [
    { text: 'Inhala profundo. Al exhalar, suelta los hombros hacia abajo.', duration: 35 },
    { text: 'En cada exhalación, imagina que sueltas una preocupación leve.', duration: 50 },
    { text: 'Aprieta los puños 5 segundos… y suelta por completo.', duration: 40 },
    { text: 'Mandíbula floja, lengua suelta, cejas relajadas.', duration: 45 },
    { text: 'No tienes que resolver todo ahora. Solo estar aquí.', duration: 50 },
    { text: 'Tres respiraciones más. Vuelve con más espacio interior.', duration: 35 },
  ],
  presleep: [
    { text: 'Apaga pantallas en tu mente. Oscuridad amable.', duration: 35 },
    { text: 'Exhala más largo que inhalar: 4 segundos entra, 6 salen.', duration: 55 },
    { text: 'Cuenta del 10 al 1 solo al exhalar. Si te pierdes, vuelve al 10.', duration: 60 },
    { text: 'Imagina un lugar seguro y aburrido — sin historia, solo calma.', duration: 55 },
    { text: 'El día ya terminó. Mañana habrá tiempo para lo pendiente.', duration: 45 },
    { text: 'Deja que el cuerpo se hunda en la cama o la silla.', duration: 40 },
  ],
  prefocus: [
    { text: 'Tres respiraciones. Hoy no necesitas mil cosas, solo la siguiente.', duration: 35 },
    { text: 'Nombra mentalmente la única tarea que más importa ahora.', duration: 45 },
    { text: 'Visualiza los primeros 2 minutos de esa tarea. Solo empezar.', duration: 50 },
    { text: 'Suelta distracciones como hojas en un río — pasan, no te arrastran.', duration: 50 },
    { text: 'Inhala energía, exhala duda. Mandíbula suelta.', duration: 40 },
    { text: 'Abre los ojos listo. Un paso a la vez.', duration: 25 },
  ],
  walk: [
    { text: 'Párate. Siente el peso en ambos pies por 20 segundos.', duration: 30 },
    { text: 'Camina muy lento. Solo nota el talón que toca el suelo.', duration: 50 },
    { text: 'Sincroniza la respiración con el paso si te ayuda.', duration: 50 },
    { text: 'Si la mente divaga, vuelve a los pies. Sin culpa.', duration: 50 },
    { text: 'Detente. Tres respiraciones. Observa cómo cambió tu ritmo.', duration: 35 },
  ],
  loving: [
    { text: 'Respira con suavidad. Trae a la mente tu propio nombre.', duration: 35 },
    { text: 'Repite mentalmente: "Que esté bien. Que esté en paz."', duration: 50 },
    { text: 'Piensa en alguien que quieres. Mismo deseo para esa persona.', duration: 50 },
    { text: 'Si aparece alguien difícil, solo desea calma — sin forzar cariño.', duration: 50 },
    { text: 'Extiende el mismo deseo a quienes pasan por la calle hoy.', duration: 45 },
    { text: 'Vuelve a ti. Cierra con una exhalación larga.', duration: 30 },
  ],
}
