/** Escuela Mejora — 20 lecciones adicionales (módulos 33–52) */

export const EXTRA_LEGENDARY_HALL = [
  { lessonId: 'clive-wearing', year: '1985', name: 'Clive Wearing', tagline: '20 segundos de presente · amnesia total' },
  { lessonId: 'broca-tan', year: '1861', name: 'Paciente Tan', tagline: 'Broca · “tan tan tan”' },
  { lessonId: 'hemispatial-neglect', year: '1978', name: 'Negligencia espacial', tagline: 'Medio mundo borrado' },
  { lessonId: 'korsakoff', year: '1889', name: 'Korsakoff', tagline: 'Confabulación · tiamina' },
  { lessonId: 'cotard-delusion', year: '1880', name: 'Cotard', tagline: '“Estoy muerto”' },
  { lessonId: 'alien-hand', year: '1980s', name: 'Mano alienígena', tagline: 'El cerebro que desobedece' },
  { lessonId: 'false-memories', year: '1995', name: 'Loftus', tagline: 'Recuerdos implantados' },
]

export const SCHOOL_LESSONS = [
  {
    id: 'glia-brain-glue',
    category: 'systems',
    title: 'Glia: el 50% del cerebro que ignoraste',
    readMin: 6,
    region: 'Astrocitos · microglía · oligodendrocitos',
    relatedExercise: 'symbols',
    hook: 'Las neuronas son estrellas, pero la glía es el escenario que las sostiene.',
    sections: [
      { h: 'Más que relleno', p: 'La mitad de las células cerebrales son glía. Astrocitos regulan glutamato, nutren neuronas y forman la barrera glía limitante. Sin ellos, las neuronas mueren en horas.' },
      { h: 'Microglía: inmune del cerebro', p: 'Patrullan sinapsis, eliminan conexiones débiles y responden a lesión. Activación crónica (estrés, sueño pobre) puede dañar neuronas — neuroinflamación.' },
      { h: 'Oligodendrocitos y velocidad', p: 'Producen mielina en SNC. Más capas = más velocidad de conducción. Esclerosis múltiple destruye mielina — señal lenta y síntomas motores/sensoriales.' },
    ],
    takeaway: 'Pensar solo en neuronas es ver la mitad del cerebro.',
    apply: 'Dormir bien y reducir estrés crónico protege microglía — tu “limpieza” sináptica.',
    reflect: '¿Qué hábito tuyo podría estar activando microglía de más?',
  },
  {
    id: 'myelin-speed',
    category: 'systems',
    title: 'Mielina: el cableado de alta velocidad',
    readMin: 5,
    region: 'Sustancia blanca · corteza · tractos de asociación',
    relatedExercise: 'corsi',
    hook: 'Un impulso sin mielina viaja a 1 m/s. Con mielina: 100 m/s.',
    sections: [
      { h: 'Saltos nodales', p: 'La mielina aísla el axón excepto en nódulos de Ranvier. El potencial de acción “salta” — conducción saltatoria. Menos energía, más rapidez.' },
      { h: 'Maduración hasta los 25', p: 'La mielinización de PFC y tractos frontales continúa en la adolescencia. Explica impulsividad adolescente y sensibilidad a cannabis — circuitos aún sin aislar.' },
      { h: 'Práctica y mielina', p: 'Estudios en músicos y atletas: más mielina en circuitos entrenados. Practica repetida no solo fortalece sinapsis — acelera cables.' },
    ],
    takeaway: 'Maestría = sinapsis fuertes + cables rápidos.',
    apply: 'Repite una habilidad lenta y correcta 10 min — la mielina responde a volumen, no a prisa.',
    reflect: '¿Qué habilidad tuya aún se siente “lenta” porque no la has practicado miles de veces?',
  },
  {
    id: 'clive-wearing',
    category: 'memory',
    title: 'Clive Wearing: 20 segundos de presente',
    readMin: 7,
    region: 'Hipocampo bilateral · memoria episódica',
    relatedExercise: 'corsi',
    hook: 'Cada despertar cree que acaba de nacer. Su diario está lleno de “ahora sí estoy despierto”.',
    sections: [
      { h: 'Encefalitis y destrucción', p: 'Virus herpes dañó hipocampo bilateral de Clive Wearing (1985). Memoria anterógrada casi cero — no retiene episodios nuevos. Memoria procedimental e implicits intactas: sigue tocando piano de memoria.' },
      { h: 'Presente perpetuo', p: 'Vive en ventana de ~20–30 segundos. Reconoce a su esposa Deborah emocionalmente pero no recuerda haberla visto hace un minuto. Su caso separa memoria episódica de habilidad.' },
      { h: 'Lección', p: 'Sin hipocampo no hay narrativa personal continua. Pero el cerebro motor y emocional siguen aprendiendo — música, rutinas, afecto inmediato.' },
    ],
    takeaway: 'Tu historia de vida es un producto hipocampal — no lo des por sentado.',
    apply: 'Escribe un episodio de hoy en 3 líneas — externaliza lo que Clive no puede retener.',
    reflect: '¿Qué momento de esta semana no quieres que se borre?',
    intensity: 'brutal',
  },
  {
    id: 'reconsolidation',
    category: 'memory',
    title: 'Reconsolidación: cada recuerdo se reescribe',
    readMin: 6,
    region: 'Hipocampo · amígdala · corteza',
    relatedExercise: 'nback',
    hook: 'Recordar no es leer un archivo — es editarlo y guardar de nuevo.',
    sections: [
      { h: 'Ventana de reconsolidación', p: 'Al recuperar un recuerdo, la traza vuelve a ser labile (inestable) durante horas. Puedes modificarla con nueva información o fármacos (estudios con propranolol en trauma).' },
      { h: 'Memoria falsa', p: 'Loftus mostró que sugerencias en reconsolidación implantan recuerdos vívidos de eventos que no ocurrieron. El cerebro prioriza coherencia narrativa sobre precisión.' },
      { h: 'Uso terapéutico', p: 'Terapias de exposición para fobia/TEPT aprovechan reconsolidación: activar miedo en contexto seguro permite reescribir la asociación amigdalar.' },
    ],
    takeaway: 'Tus recuerdos “vívidos” no son más verdaderos — son más recientes en edición.',
    apply: 'Al recordar algo doloroso, añade un dato nuevo (seguridad actual) — ayuda a reconsolidar con menos amenaza.',
    reflect: '¿Hay un recuerdo que has contado tantas veces que ya no sabes qué es original?',
  },
  {
    id: 'false-memories',
    category: 'memory',
    title: 'Memorias falsas: el experimento del shopping mall',
    readMin: 6,
    region: 'Hipocampo · PFC · redes de simulación',
    relatedExercise: 'logic',
    hook: 'El 25% de adultos “recuerda” haberse perdido en un centro comercial que nunca visitaron.',
    sections: [
      { h: 'Loftus y el mall', p: 'Sugerencias familiares + fotos falsas implantaron recuerdos de perderse de niño. Participantes describían detalles con emoción — completamente fabricados.' },
      { h: 'Por qué funciona', p: 'El cerebro no etiqueta “real” vs “imaginado”. Simular y recordar comparten redes (hipocampo, PFC). Repetir una imagen mental la consolida como episodio.' },
      { h: 'Implicaciones', p: 'Testimonios oculares fallan. Terapeutas con técnicas de “recuperación de memoria” crearon falsas acusaciones en los 90. La ciencia de memoria es forense y clínica.' },
    ],
    takeaway: 'Confianza en un recuerdo ≠ precisión del recuerdo.',
    apply: 'Antes de jurar “lo recuerdo perfecto”, busca corroboración externa.',
    reflect: '¿Tienes un recuerdo de infancia que alguien de tu familia niega?',
    intensity: 'intenso',
  },
  {
    id: 'prosopagnosia',
    category: 'systems',
    title: 'Prosopagnosia: ver caras sin reconocerlas',
    readMin: 5,
    region: 'Giro fusiforme · área de caras (FFA)',
    relatedExercise: 'symbols',
    hook: 'Brad Pitt tiene prosopagnosia. Saluda a extraños pensando que son amigos.',
    sections: [
      { h: 'Área fusiforme de caras', p: 'FFA responde selectivamente a rostros. Lesión o desarrollo atípico causa prosopagnosia: ves rasgos pero no identidad. Familiares parecen desconocidos.' },
      { h: 'Congénita vs adquirida', p: '2–3% tiene forma congénita (nunca aprendieron a reconocer bien). Adquirida por accidente o ACV. Compensan con voz, pelo, contexto, ropa.' },
      { h: 'Espejo social', p: 'Reconocer caras es automático para la mayoría — tan automático que no notas el módulo. Prosopagnosia revela que “ver cara = saber quién” no es obvio para el cerebro.' },
    ],
    takeaway: 'El reconocimiento facial es un módulo especializado, no “ver bien”.',
    apply: 'Al saludar por videollamada, di tu nombre — ayuda a quien tenga prosopagnosia leve.',
    reflect: '¿Qué otra categoría reconoces al instante sin pensar (voces, olores)?',
  },
  {
    id: 'hemispatial-neglect',
    category: 'attention',
    title: 'Negligencia espacial: medio mundo borrado',
    readMin: 6,
    region: 'Parietal derecho · red de atención espacial',
    relatedExercise: 'flanker',
    hook: 'Solo se peina la mitad derecha de la cabeza. El lado izquierdo no existe para su cerebro.',
    sections: [
      { h: 'Lesión parietal derecha', p: 'Tras ACV en parietal derecho, pacientes ignoran el hemisferio contralateral (izquierdo). No es ceguera — el ojo ve, pero la atención no asigna recursos.' },
      { h: 'Extinción', p: 'Presenta estímulo en lado sano: lo detecta. En ambos lados: solo reporta el derecho. El izquierdo se “extingue” competitivamente.' },
      { h: 'Rehabilitación', p: 'Prismas, entrenamiento de búsqueda visual, estimulación del lado negligenciado. La red parietal derecha es crítica para mapa espacial egocéntrico.' },
    ],
    takeaway: 'Atención y conciencia espacial son construcciones — se pueden perder por lesión.',
    apply: 'Haz un barrido visual consciente al entrar a un espacio — entrena red parietal.',
    reflect: '¿Qué “mitad” de tu día ignoras habitualmente (mañana vs noche, trabajo vs cuerpo)?',
    intensity: 'brutal',
  },
  {
    id: 'broca-tan',
    category: 'systems',
    title: 'Broca y el paciente Tan: el lenguaje roto',
    readMin: 7,
    region: 'Área de Broca · lóbulo frontal izquierdo',
    relatedExercise: 'stroop',
    hook: '“Tan tan tan.” Comprende todo. No puede articular una frase.',
    sections: [
      { h: 'Afasia de Broca', p: 'Lesión en giro frontal inferior izquierdo (BA 44/45). Producción telegráfica, gramática rota, esfuerzo motor al hablar. Comprensión relativamente intacta.' },
      { h: 'Wernicke al otro lado', p: 'Área de Wernicke (temporal): fluencia preservada pero sin sentido — “word salad”. Comprende poco. Broca y Wernicke demostraron modularidad del lenguaje.' },
      { h: 'Arco fascicular', p: 'Fascículo arqueado conecta ambas áreas. Lesión = repetición imposible pero comprensión/producción parciales. El lenguaje es red, no un punto.' },
    ],
    takeaway: 'Hablar y entender son circuitos distintos que se integran.',
    apply: 'Cuando busques palabras bajo estrés, tu Broca está saturado — baja carga cognitiva primero.',
    reflect: '¿Cuándo te quedaste “sin palabras” aunque supieras qué querías decir?',
    intensity: 'brutal',
  },
  {
    id: 'circadian-clocks',
    category: 'sleep',
    title: 'Relojes circadianos: tu cronobiología',
    readMin: 6,
    region: 'Núcleo supraquiasmático · melatonina · cortisol',
    relatedExercise: 'nback',
    hook: 'Tu hígado sabe qué hora es aunque no veas el reloj.',
    sections: [
      { h: 'NSQ maestro', p: 'Núcleo supraquiasmático en hipotálamo recibe luz retinal y sincroniza relojes periféricos en cada órgano. Sin luz, ciclo libre ~24.2 h.' },
      { h: 'Melatonina y cortisol', p: 'Oscuridad → pineal libera melatonina → sueño. Amanecer → cortisol pico → alerta. Luz azul nocturna suprime melatonina 2+ horas.' },
      { h: 'Cronodisrupción', p: 'Turnos nocturnos, jet lag y pantallas tarde desincronizan. Asociado a obesidad, depresión, peor consolidación. El sueño no es solo horas — es fase.' },
    ],
    takeaway: 'Dormir a la hora correcta importa tanto como dormir suficiente.',
    apply: 'Luz brillante 10 min al despertar; pantallas off 60 min antes de dormir.',
    reflect: '¿Tu horario actual pelea contra tu cronotipo (alondra/ búho)?',
  },
  {
    id: 'caffeine-adenosine',
    category: 'sleep',
    title: 'Cafeína y adenosina: deuda de sueño encubierta',
    readMin: 5,
    region: 'Receptores A1/A2A · adenosina acumulativa',
    hook: 'La cafeína no te da energía — bloquea la señal de cansancio.',
    sections: [
      { h: 'Adenosina como medidor', p: 'Cada hora despierto acumulas adenosina en SNC. Más adenosina = más presión de sueño. Durante sueño se metaboliza — despiertas “reseteado”.' },
      { h: 'Antagonismo', p: 'Cafeína compite por receptores A1/A2A sin activarlos. Bloqueas el mensaje de cansancio; la adenosina sigue acumulándose detrás del tapón.' },
      { h: 'Crash y media vida', p: 'Media vida ~5–6 h. Café a las 16:00 = 50% activo a las 22:00. Al metabolizar cafeína, adenosina acumulada golpe de golpe — el “bajón”.' },
    ],
    takeaway: 'Cafeína pospone sueño, no lo reemplaza.',
    apply: 'Último café antes de las 14:00 si duermes a las 22:00.',
    reflect: '¿Usas cafeína para enmascarar sueño insuficiente crónico?',
  },
  {
    id: 'oxytocin-social',
    category: 'emotion',
    title: 'Oxitocina: más que “hormona del amor”',
    readMin: 6,
    region: 'Hipólamo · amígdala · corteza social',
    relatedExercise: 'gonogo',
    hook: 'Aumenta confianza hacia tu tribu — y puede aumentar xenofobia hacia fuera.',
    sections: [
      { h: 'Vínculo y lactancia', p: 'Oxitocina en parto, lactancia y contacto físico fortalece apego. Libera en abrazos >20 s. Reduce amígdala ante rostros familiares.' },
      { h: 'Efectos oscuros', p: 'Estudios con spray nasal: más confianza in-group pero más desconfianza out-group. No es “molécula del amor universal” — modula coaliciones sociales.' },
      { h: 'Contexto importa', p: 'Misma molécula, efectos opuestos según situación y expectativa. Neuroquímica sin psicología social es incompleta.' },
    ],
    takeaway: 'Oxitocina refuerza lazos existentes — elige con quién la cultivas.',
    apply: 'Abrazo largo o caminata con alguien de confianza hoy — oxitocina endógena.',
    reflect: '¿Tu “tribu” actual te acerca o te cierra al mundo?',
  },
  {
    id: 'serotonin-debate',
    category: 'emotion',
    title: 'Serotonina: ¿química de la felicidad?',
    readMin: 6,
    region: 'Raphe · múltiples receptores 5-HT · modulación global',
    relatedExercise: 'stroop',
    hook: 'Los ISRS tardan semanas — la serotonina no actúa como interruptor instantáneo.',
    sections: [
      { h: 'Más que humor', p: 'Serotonina modula apetito, sueño, agresión, impulsividad, peristalsis. Neuronas del raphe proyectan a casi todo el cerebro.' },
      { h: 'ISRS y plasticidad', p: 'Inhibidores de recaptación no “suben felicidad” en días — inducen plasticidad sináptica gradual. Cambio de humor es efecto tardío de remodelación.' },
      { h: 'Debate actual', p: 'Revisión Moncrieff (2022) cuestionó evidencia causal serotonina-depresión. Consenso: es un factor entre muchos — inflamación, estrés, genética, sueño.' },
    ],
    takeaway: 'La depresión no es “falta de serotonina” — es desregulación de redes.',
    apply: 'Si tomas ISRS: dale semanas y combina con sueño, movimiento y terapia.',
    reflect: '¿Has simplificado alguna emoción tuya a “me falta X químico”?',
  },
  {
    id: 'trauma-hippocampus',
    category: 'emotion',
    title: 'Trauma y hipocampo: memoria fragmentada',
    readMin: 7,
    region: 'Hipocampo · amígdala · cortisol crónico',
    relatedExercise: 'corsi',
    hook: 'El trauma puede borrar secuencia pero intensificar sensación — amígdala hiperactiva, hipocampo apagado.',
    sections: [
      { h: 'Disociación', p: 'En amenaza extrema, amígdala domina y PFC/hipocampo bajan actividad. Recuerdos quedan fragmentados, sensoriales, sin narrativa temporal clara.' },
      { h: 'Cortisol crónico', p: 'TEPT asociado a volumen hipocampal reducido en algunos estudios — ¿causa o consecuencia? Estrés crónico inhibe neurogénesis hipocampal en modelos animales.' },
      { h: 'Recuperación', p: 'EMDR, exposición prolongada, mindfulness con evidencia. Seguridad repetida permite reconsolidación. El cerebro puede re-aprender que el presente no es el pasado.' },
    ],
    takeaway: 'Memoria traumática no es “floja” — está codificada en otro modo.',
    apply: 'Si un recuerdo te desborda: ancla en presente (pies en suelo, 5 sentidos) antes de narrarlo.',
    reflect: '¿Hay un recuerdo que viene en imágenes sin historia clara?',
    intensity: 'intenso',
  },
  {
    id: 'alexithymia',
    category: 'emotion',
    title: 'Alexitimia: sentir sin nombrar',
    readMin: 5,
    region: 'Ínsula · corteza cingulada · PFC',
    relatedExercise: 'stroop',
    hook: 'El 10% de la población tiene dificultad para identificar sus propias emociones.',
    sections: [
      { h: 'Sin palabras para sentir', p: 'Alexitimia: no “falta de emoción” sino falta de etiquetas internas. Reportan síntomas corporales (“me duele el pecho”) sin nombrar tristeza o ansiedad.' },
      { h: 'Base neural', p: 'Menor conectividad ínsula-PFC en algunos estudios. La ínsula traduce interocepción; sin etiqueta, el cuerpo habla pero la mente no traduce.' },
      { h: 'Entrenamiento', p: 'Diarios emocionales, terapia focalizada en emociones, mindfulness interoceptivo mejoran identificación con práctica — plasticidad de etiquetado.' },
    ],
    takeaway: 'Nombrar emociones no es obvio — es habilidad entrenable.',
    apply: 'Tres veces hoy: pausa y nombra emoción + sensación corporal (ej. “tensión mandíbula = ansiedad leve”).',
    reflect: '¿Qué emoción te cuesta más identificar en ti?',
  },
  {
    id: 'critical-periods',
    category: 'plasticity',
    title: 'Periodos críticos: ventanas que se cierran',
    readMin: 6,
    region: 'Corteza visual · auditiva · lenguaje',
    relatedExercise: 'symbols',
    hook: 'Después de los 7 años, un ojo vendado deja ceguera permanente. Antes, el cerebro se reconfigura.',
    sections: [
      { h: 'Hubel y Wiesel', p: 'Nobel por deprivación visual en gatos: periodo crítico temprano define columnas oculares. Sin input a tiempo, el circuito no se forma.' },
      { h: 'Lenguaje', p: 'Genie y víctimas de privación extrema: sin exposición antes de ~7–12 años, gramática nunca se domina completamente aunque vocabulario sí.' },
      { h: 'Adultos', p: 'Periodos críticos estrictos bajan con edad pero plasticidad adulta existe — más lenta, requiere más repetición y atención.' },
    ],
    takeaway: 'El cerebro joven es plástico por diseño — el adulto paga más por aprender.',
    apply: 'Si aprendes idioma o instrumento: inmersión diaria corta > sesión larga semanal.',
    reflect: '¿Qué habilidad desearías haber empezado antes del cierre de tu ventana?',
  },
  {
    id: 'cannabis-adolescent',
    category: 'plasticity',
    title: 'Cannabis adolescente y PFC en construcción',
    readMin: 6,
    region: 'PFC · endocannabinoides · mielinización',
    relatedExercise: 'gonogo',
    hook: 'El cerebro adolescente tiene más receptores CB1 en PFC que el adulto — y más vulnerable.',
    sections: [
      { h: 'Endocannabinoide natural', p: 'El sistema endocannabinoide regula apetito, memoria, plasticidad. THC exógeno lo satura — especialmente cuando PFC aún se mieliniza.' },
      { h: 'Evidencia epidemiológica', p: 'Uso frecuente antes de 18 asociado a peor rendimiento ejecutivo, mayor riesgo psicosis en vulnerables, IQ ligeramente menor en cohortes longitudinales (controversia metodológica, pero señal consistente).' },
      { h: 'Sin moralina', p: 'No es “drogas malas” simplista — es timing. El mismo compuesto en adulto con PFC maduro tiene perfil de riesgo distinto.' },
    ],
    takeaway: 'La edad del cerebro importa más que la sustancia sola.',
    apply: 'Si consumes cannabis: conoce tu cronología cerebral — PFC madura ~25.',
    reflect: '¿Qué decisiones de adolescencia afectaron tu PFC en formación?',
    intensity: 'intenso',
  },
  {
    id: 'cotard-delusion',
    category: 'emotion',
    title: 'Síndrome de Cotard: “estoy muerto”',
    readMin: 6,
    region: 'Parietal · ínsula · desconexión emocional',
    relatedExercise: 'logic',
    hook: 'Pacientes creen estar muertos, putrefactos o sin órganos. Capgras al revés: familiaridad sin realidad.',
    sections: [
      { h: 'Delirio nihilista', p: 'Cotard (1880): niegan existencia propia o de órganos. A menudo con depresión psicótica severa o lesión parietal/ínsula.' },
      { h: 'Opuesto a Capgras', p: 'Capgras: reconoces cara, no sientes familiaridad → “impostor”. Cotard: pierdes sensación de existir → “estoy muerto”. Ambos: desconexión emoción-reconocimiento.' },
      { h: 'Tratamiento', p: 'Antidepresivos, ECT en casos graves, antipsicóticos. Algunos responden a estimulación. Muestra que “sentirse vivo” tiene base neural.' },
    ],
    takeaway: 'La sensación de existir es construcción cerebral — se puede romper.',
    apply: 'Interocepción (ejercicio, respiración) refuerza señal de “estoy aquí”.',
    reflect: '¿Qué te ancla a sentirte vivo cuando el día es gris?',
    intensity: 'brutal',
  },
  {
    id: 'alien-hand',
    category: 'systems',
    title: 'Mano alienígena: cuando el cerebro desobedece',
    readMin: 6,
    region: 'Cuerpo calloso · SMA · parietal',
    relatedExercise: 'switching',
    hook: 'La mano se abrocha sola, se pelea con la otra, abre puertas sin permiso.',
    sections: [
      { h: 'Lesión callosa', p: 'Tras cirugía de cuerpo calloso o ACV, el hemisferio no dominante controla una mano con intenciones propias. El paciente no la siente como “suya”.' },
      { h: 'Utilización', p: 'Variante con lesión frontal: mano agarra objetos automáticamente (comportamiento de utilización). Red de inhibición falla — acción sin intención consciente.' },
      { h: 'Libertad y agencia', p: 'Caso filosófico: si tu mano actúa sola, ¿dónde termina “tú”? La agencia es integración callosa de ambos hemisferios.' },
    ],
    takeaway: 'Unidad corporal requiere integración — se puede fracturar.',
    apply: 'Observa un gesto automático tuyo (revisar teléfono) — mini “mano alienígena” hábitual.',
    reflect: '¿Qué parte de tu conducta actúa sin tu permiso consciente?',
    intensity: 'brutal',
  },
  {
    id: 'korsakoff',
    category: 'memory',
    title: 'Korsakoff: memoria confabulada',
    readMin: 6,
    region: 'Cuerpos mamilares · tálamo · tiamina',
    relatedExercise: 'corsi',
    hook: 'Llena los huecos con historias inventadas — y las cree con total convicción.',
    sections: [
      { h: 'Alcohol y tiamina', p: 'Déficit de vitamina B1 (tiamina) por alcoholismo crónico destruye cuerpos mamilares y tálamo dorsomedial. Amnesia anterógrada severa.' },
      { h: 'Confabulación', p: 'Sin memoria nueva, el cerebro rellena gaps con narrativas plausibles — no miente a propósito, confunde recuerdo con inferencia.' },
      { h: 'Prevención', p: 'Reversible parcialmente si se detecta temprano con tiamina IV. Tardío: daño permanente. El cerebro necesita combustible para consolidar.' },
    ],
    takeaway: 'Sin nutrición cerebral, la memoria se desmorona y el cerebro inventa.',
    apply: 'Si bebes alcohol: asegura dieta con tiamina (granos, legumbres) — no es broma neurológica.',
    reflect: '¿Has rellenado alguna vez un hueco de memoria con una historia inventada?',
    intensity: 'intenso',
  },
  {
    id: 'mirror-neurons',
    category: 'systems',
    title: 'Neuronas espejo: ¿empatía en el cerebro?',
    readMin: 6,
    region: 'Corteza premotora · ínsula · parietal inferior',
    relatedExercise: 'flanker',
    hook: 'Neuronas que disparan al hacer Y al ver hacer — base de aprendizaje por imitación.',
    sections: [
      { h: 'Descubrimiento en macacos', p: 'Rizzolatti (Parma, 1990s): neuronas en F5 disparan al agarrar Y al ver agarrar. Propuesta: base de imitación, empatía, comprensión de intención.' },
      { h: 'Debate', p: 'Evidencia en humanos es indirecta (fMRI). Críticos dicen que “espejo” es overselling — activación motora al ver acción no implica empatía automática.' },
      { h: 'Aprendizaje social', p: 'Aunque controvertido, observar expertos activa circuitos motores similares — útil para deporte, música, terapia. La imitación es aprendizaje profundo.' },
    ],
    takeaway: 'Ver hacer es parcialmente hacer — úsalo para aprender, no solo para scrollear.',
    apply: 'Antes de una tarea difícil, mira a alguien competente hacerla 2 min — activa circuitos de imitación.',
    reflect: '¿De quién imitas conductas sin darte cuenta?',
  },
]

export const SCHOOL_LESSON_META = {
  'clive-wearing': {
    caseStudy: 'Deborah Wearing escribió “Forever Today” — cada visita de Clive era “primera vez” con lágrimas de alegría.',
    myth: 'Mito: “sin memoria no hay persona”. Realidad: Clive sigue siendo músico y esposo en el instante presente.',
    cite: 'Wilson & Wearing (1995) · Sacks (2007)',
    intensity: 'brutal',
    quote: '“Es como estar despierto por primera vez, siempre.” — Clive Wearing',
  },
  'hemispatial-neglect': {
    caseStudy: 'Bisiach & Luzzatti (1978): paciente describió plaza de Milán solo con edificios del lado derecho.',
    myth: 'Mito: “si no lo veo es porque no miro”. Realidad: el ojo ve — la atención no asigna.',
    cite: 'Bisiach & Luzzatti (1978) · Karnath (2001)',
    intensity: 'brutal',
  },
  'broca-tan': {
    caseStudy: 'Tan murió en 1861; su cerebro está en conserva en la Société d’Anthropologie de París.',
    myth: 'Mito: “el lenguaje está en un solo punto”. Realidad: es red Broca-Wernicke-arco.',
    cite: 'Broca (1861) · Geschwind (1970)',
    intensity: 'brutal',
    quote: '“Tan… tan… tan.” — únicas palabras articuladas del paciente original',
  },
  'cotard-delusion': {
    caseStudy: 'Ramachandran trató paciente Cotard con espejo + calor facial para restaurar señal de “cuerpo vivo”.',
    myth: 'Mito: “es exageración dramática”. Realidad: delirio neurológico con sufrimiento extremo.',
    cite: 'Young & Leafhead (1996) · Ramachandran',
    intensity: 'brutal',
  },
  'alien-hand': {
    caseStudy: 'Paciente con AH de cuerpo calloso: la mano izquierda abrochaba camisa que la derecha desabrochaba.',
    myth: 'Mito: “posesión sobrenatural”. Realidad: desconexión hemisférica literal.',
    cite: 'Goldberg et al. (1981) · Feinberg (2009)',
    intensity: 'brutal',
  },
  'korsakoff': {
    caseStudy: 'Sacks describió pacientes que confabulaban historias de guerra que nunca vivieron para llenar amnesia.',
    myth: 'Mito: “inventa porque es mentiroso”. Realidad: confabulación es síntoma, no carácter.',
    cite: 'Victor et al. (1971) · Sacks (1985)',
    intensity: 'brutal',
  },
}
